# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN npm install --production --ignore-scripts

# Copy source
COPY . .

# Start MCP server over stdio
CMD ["node", "src/bin/promptx.js", "mcp-server"]
